datas = "results"
delete_id = "delete_id"
org_unit_id="org_unit_id"
add_success = "NTE_01"
update_success = "NTE_03"
delete_success = "NTE_04"
results = "results"
update_id = "update_id"
error = "NTE-02"
talent_acquisition="Talent_Acquisition/talent_acquisition"
job_openings_table_query="job_openings_table_query"
job_openings_table_query_row="job_openings_table_query_row"
job_openings_table_key=['id','row_number','job_title','date_opened','target_date','number_of_positions']
offer_candidate_table_query="offer_candidate_table_query"
offer_candidate_table_query_row="offer_candidate_table_query_row"
offer_candidate_table_query_row_candidate="offer_candidate_table_query_row_candidate"
offer_candidate_dropdown_query="offer_candidate_dropdown_query"
on_boarding_table_query="on_boarding_table_query"
offer_candidate_details="offer_candidate_details"
candidate_dropdown_query="candidate_dropdown_query"
offer_candidate_table_key=['id','row_number','name','address','primary_email','secondary_email','phone_numner','mobile_number']
offer_table_key=['id','row_number','name','address','offer_release']
on_boarding_table_key=['id','row_number','name','Email']
ta_check_offer_name="ta_check_offer_name"
status_already_exists='ERR0020'
alreadyExit = 'ERR0101'
candidate_asset_details_query = "candidate_asset_details_query"
offer_candidate_table_query_row_candidate = "offer_candidate_table_query_row_candidate"
ta_job_title_drop_down = "ta_job_title_drop_down"
job_title_info = "job_title_info"
ta_fetch_reference_id = "ta_fetch_reference_id"
ta_fetch_offer_declined_status = 'ta_fetch_offer_declined_status'
ta_offer_count="ta_offer_count"
ta_offer_details="ta_offer_details"
ta_offer_details_row="ta_offer_details_row"