# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_admin', '0001_initial'),
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCMS_Attendance_Late_Early_Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('late_grace_time', models.TimeField(blank=True, null=True)),
                ('late_arrival_deduct_count', models.IntegerField(blank=True, null=True)),
                ('late_arrival_day_deduct', models.FloatField(blank=True, null=True)),
                ('early_grace_time', models.TimeField(blank=True, null=True)),
                ('early_departs_deduct_count', models.IntegerField(blank=True, null=True)),
                ('early_departs_day_deduct', models.FloatField(blank=True, null=True)),
                ('process_start_month', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_time_attendance_management_hcms_attendance_late_early_policy_related', to=settings.AUTH_USER_MODEL)),
                ('emp_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.HCMS_Shift_Master')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_time_attendance_management_hcms_attendance_late_early_policy_related', to=settings.AUTH_USER_MODEL)),
                ('policy_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_period_ref_item_id', to='system_admin.Reference_Items')),
            ],
            options={
                'db_table': 'hcms_attendance_late_early_policy',
            },
        ),
        migrations.CreateModel(
            name='HCMS_Leave_Of_Absent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('end_day', models.IntegerField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_time_attendance_management_hcms_leave_of_absent_related', to=settings.AUTH_USER_MODEL)),
                ('emp_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.HCMS_Shift_Master')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_time_attendance_management_hcms_leave_of_absent_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_leave_of_absent',
            },
        ),
        migrations.CreateModel(
            name='HCMS_Leave_Type_Absent_Rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_time_attendance_management_hcms_leave_type_absent_rel_related', to=settings.AUTH_USER_MODEL)),
                ('leave_of_absent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_attendance_management.HCMS_Leave_Of_Absent')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_ref_item_id', to='system_admin.Reference_Items')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_time_attendance_management_hcms_leave_type_absent_rel_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_leave_type_absent_rel',
            },
        ),
        migrations.CreateModel(
            name='HCMS_Permission_Request_Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('perm_start_month', models.IntegerField(blank=True, null=True)),
                ('perm_request_count', models.FloatField(blank=True, null=True)),
                ('perm_request_per_day', models.FloatField(blank=True, null=True)),
                ('perm_max_hour', models.TimeField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_time_attendance_management_hcms_permission_request_configuration_related', to=settings.AUTH_USER_MODEL)),
                ('emp_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.HCMS_Shift_Master')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_time_attendance_management_hcms_permission_request_configuration_related', to=settings.AUTH_USER_MODEL)),
                ('perm_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perm_period_ref_item_id', to='system_admin.Reference_Items')),
            ],
            options={
                'db_table': 'hcms_permission_request_conf',
            },
        ),
    ]
