# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_management', '0001_initial'),
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCMS_TI_Custom_Rating_Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_rating_scheme_name', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_inventory_hcms_ti_custom_rating_scheme_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_inventory_hcms_ti_custom_rating_scheme_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ti_custom_rating_scheme',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TI_Custom_Rating_Scheme_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_rating_name', models.TextField(blank=True, null=True)),
                ('custom_rating_value', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_inventory_hcms_ti_custom_rating_scheme_relation_related', to=settings.AUTH_USER_MODEL)),
                ('custom_rating_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Custom_Rating_Scheme')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_inventory_hcms_ti_custom_rating_scheme_relation_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ti_custom_rating_scheme_relation',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TI_Role_Critical_Success_Factors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('factors_crit_succ_fact', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_inventory_hcms_ti_role_critical_success_factors_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ti_role_critical_success_factor',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TI_Role_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role_title', models.CharField(blank=True, max_length=200, null=True)),
                ('role_req_work_exp', models.IntegerField(blank=True, null=True)),
                ('role_pref_edu', models.CharField(blank=True, max_length=200, null=True)),
                ('role_need', models.TextField(blank=True, null=True)),
                ('role_resp', models.TextField(blank=True, null=True)),
                ('role_travel', models.BooleanField()),
                ('role_req_no_of_resource', models.IntegerField(blank=True, default=1, null=True)),
                ('role_org_unit', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('role_grade', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('role_depts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_inventory_hcms_ti_role_details_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_inventory_hcms_ti_role_details_related', to=settings.AUTH_USER_MODEL)),
                ('role_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_org', to='organization_management.OrganizationInfo')),
                ('role_reports_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Role_Details')),
                ('role_type_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_type_reference_item', to='system_admin.Reference_Items')),
            ],
            options={
                'db_table': 'hcms_ti_role_details',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TI_Role_KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kpi_definition', models.TextField(blank=True, null=True)),
                ('kpi_plan', models.FloatField()),
                ('kpi_starting_perf', models.FloatField()),
                ('kpi_units', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_inventory_hcms_ti_role_kpi_related', to=settings.AUTH_USER_MODEL)),
                ('kpi_custom_rating_scheme_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Custom_Rating_Scheme')),
                ('kpi_measure_frequency_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_measure_frequency_refitem_id', to='system_admin.Reference_Items')),
                ('kpi_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Role_Details')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_inventory_hcms_ti_role_kpi_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ti_role_kpi',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TI_Role_KPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kpo_statement', models.TextField(blank=True, null=True)),
                ('kpo_outcome', models.TextField(blank=True, null=True)),
                ('kpo_target_date', models.TextField(blank=True, null=True)),
                ('kpo_performance_std', models.TextField(blank=True, null=True)),
                ('kpo_plan', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_inventory_hcms_ti_role_kpo_related', to=settings.AUTH_USER_MODEL)),
                ('kpo_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Role_Details')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_inventory_hcms_ti_role_kpo_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ti_role_kpo',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TI_Role_SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('skillset_applicable', models.BooleanField()),
                ('skillset_depts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_inventory_hcms_ti_role_skillset_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_inventory_hcms_ti_role_skillset_related', to=settings.AUTH_USER_MODEL)),
                ('skillset_competency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_type_reference_item', to='system_admin.Reference_Items')),
                ('skillset_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Role_Details')),
                ('skillset_skill_level_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_level_reference_item', to='system_admin.Reference_Items')),
            ],
            options={
                'db_table': 'hcms_ti_role_skillset',
            },
        ),
        migrations.AddField(
            model_name='hcms_ti_role_critical_success_factors',
            name='factors_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Role_Details'),
        ),
        migrations.AddField(
            model_name='hcms_ti_role_critical_success_factors',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_inventory_hcms_ti_role_critical_success_factors_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
