# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_management', '0001_initial'),
        ('system_admin', '0001_initial'),
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCMS_TM_CompAssess_Accolades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ca_accolades_title', models.CharField(max_length=500)),
                ('ca_accolades_year', models.IntegerField()),
                ('ca_accolades_quarter', models.IntegerField()),
                ('ca_accolades_desc', models.TextField()),
                ('ca_accolades_awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_management.OrganizationInfo')),
                ('ca_accolades_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.EmployeeInfo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_management_hcms_tm_compassess_accolades_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_management_hcms_tm_compassess_accolades_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_tm_comp_assess_accolades',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TM_Competency_Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('comp_assess_competency', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('comp_assess_score', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('comp_assess_perf_history', models.TextField(blank=True, null=True)),
                ('comp_assess_work_areas', models.TextField(blank=True, null=True)),
                ('comp_assess_year', models.IntegerField(blank=True, null=True)),
                ('comp_assess_quarter', models.IntegerField(blank=True, null=True)),
                ('comp_assess_comp_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.Reference_Item_Category')),
                ('comp_assess_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.EmployeeInfo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_management_hcms_tm_competency_assessment_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_management_hcms_tm_competency_assessment_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_tm_competency_assessment',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TM_TalentProfile_Per_Pot_Ranges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tp_cat_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tp_range_1_from', models.IntegerField(blank=True, null=True)),
                ('tp_range_1_to', models.IntegerField(blank=True, null=True)),
                ('tp_range_2_from', models.IntegerField(blank=True, null=True)),
                ('tp_range_2_to', models.IntegerField(blank=True, null=True)),
                ('tp_range_3_from', models.IntegerField(blank=True, null=True)),
                ('tp_range_3_to', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_management_hcms_tm_talentprofile_per_pot_ranges_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_management_hcms_tm_talentprofile_per_pot_ranges_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_tm_per_pot_ranges',
            },
        ),
    ]
