# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_management', '0001_initial'),
        ('organization_management', '0001_initial'),
        ('talent_inventory', '0001_initial'),
        ('system_admin', '0001_initial'),
        ('objective_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCMS_PM_Assessment_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_form_finalised_status', models.BooleanField(default=False)),
                ('assessment_year', models.CharField(blank=True, max_length=10, null=True)),
                ('assessment_quarter', models.IntegerField(blank=True, null=True)),
                ('assessment_form_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.EmployeeInfo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_performance_assessment_hcms_pm_assessment_form_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_performance_assessment_hcms_pm_assessment_form_related', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_management.OrganizationInfo')),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_management.OrganizationUnit')),
            ],
            options={
                'db_table': 'hcms_pm_assessment_form',
            },
        ),
        migrations.CreateModel(
            name='HCMS_PM_Assessment_Form_KRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_form_kpi_weightage', models.IntegerField(blank=True, null=True)),
                ('assessment_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_assessment.HCMS_PM_Assessment_Form')),
                ('assessment_form_okr_kra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objective_setting.HCMS_PM_Key_Result')),
                ('assessment_form_role_kra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Role_KPI')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_performance_assessment_hcms_pm_assessment_form_kra_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_performance_assessment_hcms_pm_assessment_form_kra_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_pm_assessment_form_kra',
            },
        ),
        migrations.CreateModel(
            name='HCMS_PM_Assessment_Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_rating', models.FloatField(blank=True, null=True)),
                ('assessment_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_assessment.HCMS_PM_Assessment_Form')),
                ('assessment_form_okr_kra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_form_kpi', to='objective_setting.HCMS_PM_Key_Result')),
                ('assessment_form_role_kra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Role_KPI')),
                ('assessment_process_assessor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_category_refitem', to='system_admin.Reference_Items')),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_assessor_id', to='employee_management.EmployeeInfo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_performance_assessment_hcms_pm_assessment_process_related', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.EmployeeInfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_performance_assessment_hcms_pm_assessment_process_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_pm_assessment_process',
            },
        ),
        migrations.CreateModel(
            name='HCMS_PM_Assessment_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_year', models.IntegerField(blank=True, null=True)),
                ('schedule_quarter', models.IntegerField(blank=True, null=True)),
                ('schedule_name', models.TextField(blank=True, null=True)),
                ('assessment_cycle_starts', models.DateField(blank=True, null=True)),
                ('assessment_cycle_ends', models.DateField(blank=True, null=True)),
                ('objective_setting_day_count', models.IntegerField(blank=True, null=True)),
                ('objective_setting_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_performance_assessment_hcms_pm_assessment_schedule_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_performance_assessment_hcms_pm_assessment_schedule_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_pm_assessment_schedule',
            },
        ),
        migrations.CreateModel(
            name='HCMS_PM_Assessment_Schedule_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assess_type_day_count', models.IntegerField(blank=True, null=True)),
                ('schedule_start_date', models.DateField(blank=True, null=True)),
                ('assessment_schedule_sequence', models.IntegerField(blank=True, null=True)),
                ('assessment_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_assessment.HCMS_PM_Assessment_Schedule')),
                ('assessor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.Reference_Items')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_performance_assessment_hcms_pm_assessment_schedule_details_related', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.EmployeeInfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_performance_assessment_hcms_pm_assessment_schedule_details_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_pm_assessment_schedule_details',
            },
        ),
        migrations.CreateModel(
            name='HCMS_PM_Assessor_Access_Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessor_access', models.BooleanField()),
                ('assessment_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_assessment.HCMS_PM_Assessment_Form')),
                ('assessor_view_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessor_view_id', to='system_admin.Reference_Items')),
                ('assessor_viewer_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessor_viewer_id', to='system_admin.Reference_Items')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_performance_assessment_hcms_pm_assessor_access_matrix_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_performance_assessment_hcms_pm_assessor_access_matrix_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_pm_assessor_access_matrix',
            },
        ),
        migrations.CreateModel(
            name='HCMS_PM_Assessor_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessor_feedback', models.TextField(blank=True, null=True)),
                ('learning_pointers', models.TextField(blank=True, null=True)),
                ('assessment_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_assessment.HCMS_PM_Assessment_Form')),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.EmployeeInfo')),
                ('assessor_type_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessor_type_refitem', to='system_admin.Reference_Items')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_performance_assessment_hcms_pm_assessor_info_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_performance_assessment_hcms_pm_assessor_info_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_pm_assessor_info',
            },
        ),
    ]
