# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-02 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20201029_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_reference',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='output_file2',
        ),
    ]
