# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-14 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NTree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okr_accessrights',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.RoleInfo'),
        ),
    ]
