# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-19 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='output_file1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='output_file2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
