# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20201019_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='output_file3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='output_file4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='output_file5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='output_file6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
