# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_admin', '0001_initial'),
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCMS_IM_Corrective_Action_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_item_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_incident_management_hcms_im_corrective_action_log_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_im_corrective_action_log',
            },
        ),
        migrations.CreateModel(
            name='HCMS_IM_Impact_Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('environmental_financial_value', models.FloatField(blank=True, null=True)),
                ('environmental_impact_detail', models.TextField(blank=True, null=True)),
                ('hr_financial_value', models.FloatField(blank=True, null=True)),
                ('hr_impact_detail', models.TextField(blank=True, null=True)),
                ('materials_financial_value', models.FloatField(blank=True, null=True)),
                ('materials_impact_detail', models.TextField(blank=True, null=True)),
                ('machinery_financial_value', models.FloatField(blank=True, null=True)),
                ('machinery_impact_detail', models.TextField(blank=True, null=True)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('other_risks', models.TextField(blank=True, null=True)),
                ('business_impact', models.TextField(blank=True, null=True)),
                ('business_activities_affected', models.TextField(blank=True, null=True)),
                ('minimum_recovery_time', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_incident_management_hcms_im_impact_analysis_related', to=settings.AUTH_USER_MODEL)),
                ('environmental_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_currency_reference_id', to='system_admin.Reference_Items')),
                ('hr_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_currency_reference_id', to='system_admin.Reference_Items')),
            ],
            options={
                'db_table': 'hcms_im_impact_analysis',
            },
        ),
        migrations.CreateModel(
            name='HCMS_IM_Incident_Evidence_Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('path', models.CharField(max_length=100, null=True)),
                ('extension', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_incident_management_hcms_im_incident_evidence_attachments_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_im_incident_evidence_attachments',
            },
        ),
        migrations.CreateModel(
            name='HCMS_IM_Incident_Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('treatment', models.CharField(blank=True, max_length=150, null=True)),
                ('injury_notes', models.TextField(blank=True, null=True)),
                ('body_part_laterality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_part_laterality_id', to='system_admin.Reference_Items')),
                ('body_part_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_part_id', to='system_admin.Reference_Items')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_incident_management_hcms_im_incident_injury_related', to=settings.AUTH_USER_MODEL)),
                ('illness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illness_reference_id', to='system_admin.Reference_Items')),
            ],
            options={
                'db_table': 'hcms_im_incident_injury',
            },
        ),
        migrations.CreateModel(
            name='HCMS_IM_Incident_Investigation_Question_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('investigation_question', models.TextField(blank=True, null=True)),
                ('investigation_answer', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_incident_management_hcms_im_incident_investigation_question_answer_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_im_investigation_question_answer',
            },
        ),
        migrations.CreateModel(
            name='HCMS_IM_Incident_Investigation_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_incident_management_hcms_im_incident_investigation_team_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_im_investigation_team_info',
            },
        ),
        migrations.CreateModel(
            name='HCMS_IM_Incident_Involved_Parties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('incident_involved_party_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_incident_management_hcms_im_incident_involved_parties_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_im_incident_involved_parties',
            },
        ),
        migrations.CreateModel(
            name='HCMS_IM_Incident_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('incident_subject', models.CharField(blank=True, max_length=150, null=True)),
                ('incident_code', models.CharField(blank=True, max_length=50, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_description', models.TextField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_trigger_info', models.TextField(blank=True, null=True)),
                ('incident_risk_details', models.TextField(blank=True, null=True)),
                ('incident_resolution_status', models.CharField(blank=True, max_length=20, null=True)),
                ('incident_investigation_required_flag', models.BooleanField(default=True)),
                ('root_cause_man', models.TextField(blank=True, null=True)),
                ('root_cause_material', models.TextField(blank=True, null=True)),
                ('root_cause_management_system', models.TextField(blank=True, null=True)),
                ('root_cause_machine', models.TextField(blank=True, null=True)),
                ('root_cause_method', models.TextField(blank=True, null=True)),
                ('root_cause_environment', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_incident_management_hcms_im_incident_record_related', to=settings.AUTH_USER_MODEL)),
                ('incident_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_category_refitem', to='system_admin.Reference_Items')),
                ('incident_reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_reported_by_id', to='employee_management.EmployeeInfo')),
                ('incident_reported_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_reported_mode_refitem', to='system_admin.Reference_Items')),
                ('incident_severity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_severity_type_refitem', to='system_admin.Reference_Items')),
                ('incident_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_type_refitem', to='system_admin.Reference_Items')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_incident_management_hcms_im_incident_record_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_im_incident_record',
            },
        ),
        migrations.CreateModel(
            name='HCMS_IM_Solution_Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('corrective_measure', models.TextField(blank=True, null=True)),
                ('preventive_measure', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_incident_management_hcms_im_solution_proposal_related', to=settings.AUTH_USER_MODEL)),
                ('incident_detail_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_detail_record_solution_proposal_id', to='incident_management.HCMS_IM_Incident_Record')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_incident_management_hcms_im_solution_proposal_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_im_solution_proposal',
            },
        ),
        migrations.AddField(
            model_name='hcms_im_incident_involved_parties',
            name='incident_detail_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_detail_record_id', to='incident_management.HCMS_IM_Incident_Record'),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_involved_parties',
            name='incident_involved_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_involved_employee_id', to='employee_management.EmployeeInfo'),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_involved_parties',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_incident_management_hcms_im_incident_involved_parties_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_investigation_team',
            name='incident_detail_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_detail_record_investigation_team_id', to='incident_management.HCMS_IM_Incident_Record'),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_investigation_team',
            name='investigation_team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_investigation_member_id', to='employee_management.EmployeeInfo'),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_investigation_team',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_incident_management_hcms_im_incident_investigation_team_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_investigation_question_answer',
            name='incident_detail_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_detail_record_qa_id', to='incident_management.HCMS_IM_Incident_Record'),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_investigation_question_answer',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_incident_management_hcms_im_incident_investigation_question_answer_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_injury',
            name='incident_detail_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_detail_record_injury_id', to='incident_management.HCMS_IM_Incident_Record'),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_injury',
            name='incident_injury_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injury_type_id', to='system_admin.Reference_Items'),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_injury',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_incident_management_hcms_im_incident_injury_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_evidence_attachments',
            name='incident_detail_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_detail_record_attachment_id', to='incident_management.HCMS_IM_Incident_Record'),
        ),
        migrations.AddField(
            model_name='hcms_im_incident_evidence_attachments',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_incident_management_hcms_im_incident_evidence_attachments_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_im_impact_analysis',
            name='incident_detail_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_detail_record_impact_analysis_id', to='incident_management.HCMS_IM_Incident_Record'),
        ),
        migrations.AddField(
            model_name='hcms_im_impact_analysis',
            name='machinery_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery_currency_reference_id', to='system_admin.Reference_Items'),
        ),
        migrations.AddField(
            model_name='hcms_im_impact_analysis',
            name='materials_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_currency_reference_id', to='system_admin.Reference_Items'),
        ),
        migrations.AddField(
            model_name='hcms_im_impact_analysis',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_incident_management_hcms_im_impact_analysis_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_im_corrective_action_log',
            name='incident_detail_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_detail_record_cal_id', to='incident_management.HCMS_IM_Incident_Record'),
        ),
        migrations.AddField(
            model_name='hcms_im_corrective_action_log',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_incident_management_hcms_im_corrective_action_log_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_im_corrective_action_log',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrective_action_owner', to='employee_management.EmployeeInfo'),
        ),
    ]
