comprehensive_management = 'Comprehensive_Management/comprehensive_management'
template_name = "comprehensive_management/base_employee.html"
employee_id = "employee_id"
no_data_found = "No Data Found"
comprehensive_employee_personal_fetch = "comprehensive_employee_personal_fetch"
comprehensive_employee_skill_fetch = "comprehensive_employee_skill_fetch"
comprehensive_employee_experience_fetch = "comprehensive_employee_experience_fetch"
comprehensive_employee_certification_fetch = "comprehensive_employee_certification_fetch"
comprehensive_employee_education_fetch = "comprehensive_employee_education_fetch"
status = "status"
skills = "skills"
experience = "experience"
certification = "certification"
education_result = "education_result"
spouse_name = "spouse_name"
spouse_info = "spouse_info"
sdob = "sdob"
father_name = "father_name"
father_info = "father_info"
fdob = "fdob"
mother_name = "mother_name"
mother_info = "mother_info"
mdob = "mdob"
marital_status = "marital_status"
no_of_children = "no_of_children"
marital_info = "marital_info"
empty = ""
comma = " , "
children = " Children"
zero = '0'
comprehensive_assessment_form_id_fetch="comprehensive_assessment_form_id_fetch"
comprehensive_assessment_kpi_detail_fetch="comprehensive_assessment_kpi_detail_fetch"
comprehensive_assessment_process_detail_fetch="comprehensive_assessment_process_detail_fetch"
comprehensive_employee_objective_form_id_fetch="comprehensive_employee_objective_form_id_fetch"
comprehensive_employee_cascaded_objective_fetch="comprehensive_employee_cascaded_objective_fetch"
comprehensive_employee_role_objective_fetch="comprehensive_employee_role_objective_fetch"
comprehensive_employee_objective_fetch="comprehensive_employee_objective_fetch"




