# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_system_admin_countryinfo_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_system_admin_countryinfo_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'country_info',
            },
        ),
        migrations.CreateModel(
            name='PermissionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_system_admin_permissioninfo_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_system_admin_permissioninfo_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'hcms_permission',
            },
        ),
        migrations.CreateModel(
            name='Reference_Item_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('refitem_category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('refitem_category_code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('refitem_category_desc', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_system_admin_reference_item_category_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_system_admin_reference_item_category_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['refitem_category_name'],
                'db_table': 'reference_item_category',
            },
        ),
        migrations.CreateModel(
            name='Reference_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('refitems_name', models.TextField(blank=True, null=True)),
                ('refitems_code', models.CharField(blank=True, max_length=5, null=True)),
                ('is_systemdata', models.BooleanField(default=False)),
                ('refitems_desc', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_system_admin_reference_items_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_system_admin_reference_items_related', to=settings.AUTH_USER_MODEL)),
                ('refitems_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.Reference_Item_Category')),
            ],
            options={
                'ordering': ['refitems_name'],
                'db_table': 'reference_items',
            },
        ),
        migrations.CreateModel(
            name='Reference_Items_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_system_admin_reference_items_link_related', to=settings.AUTH_USER_MODEL)),
                ('from_refitems_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_category', to='system_admin.Reference_Items')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_system_admin_reference_items_link_related', to=settings.AUTH_USER_MODEL)),
                ('to_refitems_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_category', to='system_admin.Reference_Items')),
            ],
            options={
                'db_table': 'reference_items_link',
            },
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('org_id', models.IntegerField(blank=True, default=0, null=True)),
                ('org_unit_id', models.IntegerField(blank=True, default=0, null=True)),
                ('role_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0], null=True, size=None)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_system_admin_roleinfo_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_system_admin_roleinfo_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'hcms_role',
            },
        ),
        migrations.CreateModel(
            name='RolePermissionRelationShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group_id', models.IntegerField(blank=True, default=0, null=True)),
                ('access_datas', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_system_admin_rolepermissionrelationship_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_system_admin_rolepermissionrelationship_related', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.PermissionInfo')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.RoleInfo')),
            ],
            options={
                'ordering': ['role'],
                'db_table': 'role_permission_rel',
            },
        ),
        migrations.CreateModel(
            name='ScanTableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_table', models.CharField(blank=True, max_length=80, null=True)),
                ('check_table', models.CharField(blank=True, max_length=80, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_system_admin_scantableinfo_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_system_admin_scantableinfo_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scan_table_info',
            },
        ),
        migrations.CreateModel(
            name='SearchTableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('search_keyword', models.CharField(blank=True, max_length=150, null=True)),
                ('search_type', models.CharField(blank=True, max_length=80, null=True)),
                ('search_data', models.CharField(blank=True, max_length=150, null=True)),
                ('search_link', models.CharField(blank=True, max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_system_admin_searchtableinfo_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_system_admin_searchtableinfo_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_table_info',
            },
        ),
        migrations.CreateModel(
            name='StateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('state_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_master', to='system_admin.CountryInfo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_system_admin_stateinfo_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_system_admin_stateinfo_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'state_info',
            },
        ),
        migrations.CreateModel(
            name='SystemParamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('module_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sys_param_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sys_param_var_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sys_param_val', models.CharField(blank=True, max_length=200, null=True)),
                ('sys_param_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_system_admin_systemparaminfo_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_system_admin_systemparaminfo_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_param_info',
            },
        ),
        migrations.AddIndex(
            model_name='stateinfo',
            index=models.Index(fields=['is_active'], name='state_info_is_acti_b2a2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermissionrelationship',
            index=models.Index(fields=['permission'], name='role_permis_permiss_146280_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermissionrelationship',
            index=models.Index(fields=['id', 'is_active'], name='role_permission_idx1'),
        ),
        migrations.AddIndex(
            model_name='rolepermissionrelationship',
            index=models.Index(fields=['is_active'], name='role_permission_rel_idx2'),
        ),
        migrations.AddIndex(
            model_name='roleinfo',
            index=models.Index(fields=['name'], name='hcms_role_name_f524ea_idx'),
        ),
        migrations.AddIndex(
            model_name='roleinfo',
            index=models.Index(fields=['id', 'is_active'], name='role_idx1'),
        ),
        migrations.AddIndex(
            model_name='roleinfo',
            index=models.Index(fields=['is_active'], name='role_idx2'),
        ),
        migrations.AddIndex(
            model_name='permissioninfo',
            index=models.Index(fields=['name'], name='hcms_permis_name_fbd40e_idx'),
        ),
        migrations.AddIndex(
            model_name='permissioninfo',
            index=models.Index(fields=['id', 'is_active'], name='permission_idx1'),
        ),
        migrations.AddIndex(
            model_name='permissioninfo',
            index=models.Index(fields=['is_active'], name='permission_idx2'),
        ),
        migrations.AddIndex(
            model_name='countryinfo',
            index=models.Index(fields=['is_active'], name='country_inf_is_acti_442dec_idx'),
        ),
    ]
