asset_management = "Asset_Management/asset_management"
as_mgnt_employee_info_fetch = "as_mgnt_employee_info_fetch"
asset_list_if_fetch = "asset_list_if_fetch"
asset_list_else_fetch = "asset_list_else_fetch"
asset_list_house_fetch = "asset_list_house_fetch"
insert_asset_data = "insert_asset_data"
fetch_asset_list_data_allocated = "fetch_asset_list_data_allocated"
ast_val = "ast_val"
list_asset = "list_asset"
ast_typ = "ast_typ"
val= 'val'
refitems_name = "refitems_name" 
asset_details_update='asset_details_update'
remove_query='remove_query'
fetch_refitemscode='fetch_refitemscode'
fetch_emp_name='fetch_emp_name'
fetch_emp_id='fetch_emp_id'
fetch_refitem_id='fetch_refitem_id'
asset_type_code_fetch='asset_type_code_fetch'
refitem_fetch='refitem_fetch'
hrms_asset_info_update='hrms_asset_info_update'
asset_list_else_fetch_houseval='asset_list_else_fetch_houseval'
am_org_fetch = 'am_org_fetch'
am_orgunit_fetch = 'am_orgunit_fetch'
sel_asset_org_unit_val = 'sel_asset_org_unit_val'
sel_asset_org_val = 'sel_asset_org_val'
am_fetch_dept_list = 'am_fetch_dept_list'
