"""
Django settings for HCMS project. 
 
Generated by 'django-admin startproject' using Django 1.11.5.
 
For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/
 
For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import os
import getpass
# Build paths inside the project like this: os.path.join(BASE_DIR, ...) 
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
  
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/ 
  
# SECURITY WARNING: keep the secret key used in production secret!  
SECRET_KEY = '6$n4(6isjoh*vlr_-7izkyr&-g%h-%-3i@dde5!tvx-5xi930@'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 
ALLOWED_HOSTS = ["*"]  
# Application definition       
INSTALLED_APPS = [          
    'django.contrib.admin',     
    'django.contrib.auth',     
    'django.contrib.contenttypes',  
    'django.contrib.sessions',    
    'django.contrib.messages',        
    'django.contrib.staticfiles',   
    'activity_log',   
    'hcms_dashboard',     
    'HCMS_System_Admin.system_admin',   
    'HCMS_System_Admin.correspondence_mgt',  
    'HCMS_System_Admin.help_topics', 
    'HRMS_Foundation.organization_management',
    'Talent_Inventory.talent_inventory',     
    'HRMS_Foundation.attendance_management',
    'HRMS_Foundation.employee_management',
    'Talent_Assessment.talent_assessment',   
    'Comprehensive_Management.comprehensive_management',  
    'Incident_Management.incident_management',  
    'Workforce_Administration.shift_management',                         
    'Workforce_Administration.time_attendance_management', 
    'Workforce_Administration.workforce_administration',
    'HRMS_Foundation.payroll_management',   
    'Asset_Management.asset_management',     
    'Exit_Management.exit_management',
    'Talent_Acquisition.talent_acquisition',
    'Workforce_Planning.workforce_planning',  
    'NTree', 
    'Performance_Management.objective_setting',
    'Performance_Management.performance_assessment',
    'Succession_Planning.succession_planning', 
    'Talent_Management.talent_management',
    'Learning_Management.learning_management',
    'Performance_Assessment.PerformanceAssessment' ,
    'Correspondance_Management_Static.CorrespondanceManagementStatic',
    'MyNext_Dashboard.communication_empowerment', 
    'corsheaders', # browser cross orgin error 
    'rest_framework',# CES API
    'payment',
 
]   
CORS_ORIGIN_ALLOW_ALL = True #browser cross orgin error

MIDDLEWARE = [  
    'corsheaders.middleware.CorsMiddleware',#browser cross orgin error
    'django.middleware.security.SecurityMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',    
    'django.contrib.sessions.middleware.SessionMiddleware', 
    #'django_session_timeout.middleware.SessionTimeoutMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware',     
    'django.contrib.messages.middleware.MessageMiddleware', 
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'HCMS.urls'
TEMPLATES = [
    {  
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  
        'DIRS': [os.path.join(BASE_DIR, "templates")],   
        'APP_DIRS': True,          
        'OPTIONS': {   
            'context_processors': [        
                'django.template.context_processors.debug',      
                'django.template.context_processors.request', 
                'django.contrib.auth.context_processors.auth',     
                'django.contrib.messages.context_processors.messages',        
            ],         
        }, 
    },            
]       
WSGI_APPLICATION = 'HCMS.wsgi.application'      
# Database       
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases          
DATABASES = {          
    'default': {  
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'next_hcms_live', 
        'USER': 'next',         
        'PASSWORD': 'next', 
        'HOST': 'localhost',         
        'PORT': '5432', 
    }    
}  
             
# Password validation                     
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators        
AUTH_PASSWORD_VALIDATORS = [       
    {                                                                                                                                                                                                  
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',   
    },   
    {        
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',   
    },       
    { 
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',      
    },     
    {     
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',     
    },      
]      
   
# Internationalization        
# https://docs.djangoproject.com/en/1.11/topics/i18n/                  
LANGUAGE_CODE = 'en-us'               
TIME_ZONE = 'UTC'     
USE_I18N = True          
USE_L10N = True   
USE_TZ = True 
    
# Static files (CSS, JavaScript, Images)      
# https://docs.djangoproject.com/en/1.11/howto/static-files/  
STATIC_URL = '/static/'       
STATICFILES_DIRS = [   
    os.path.join(BASE_DIR, "static"), 
]                  
SESSION_EXPIRE_AT_BROWSER_CLOSE = True 
LOGIN_URL = '/'

MEDIA_ROOT = '/home/nextaps/.hcms/uploads/' 
#STATIC_ROOT = 'static/.static_cs/'
MEDIA_URL = '/media/' 
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880
### Mail Configuration 
EMAIL_USE_TLS = True   
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 
EMAIL_HOST = 'smtp.yandex.com'    
EMAIL_HOST_USER = 'hcmsadmin@nexttechnosolutions.co.in'    
EMAIL_HOST_PASSWORD = 'N3xt@dd33'   
EMAIL_PORT = 587   
SENDER_NAME='Transform-NEXT-HCMS'   
SENDER_JOIN1 = 'Job Query NEXT Inc Web Portal'   
SENDER_JOIN2 = 'NEXT Inc Web Portal User Name & Password' 
SENDER_JOIN3 = 'NEXT Inc E-Verification User Name & Password'
SENDER_JOIN4 = 'Candidate OTP Generation'
SENDER_JOIN5 = 'NEXT Inc New Candidate Applied'  
SENDER_JOIN6 = 'NEXT Inc Take Your Digital Assessment User Name & Password'
REACH_US='Reach Us - NEXT Inc' 
#Logger   
LOGGING = {   
    'version': 1,    
    'disable_existing_loggers': False,  
    'formatters' : {
        'standard' : {     
            'format' : '%(asctime)s [%(levelname)s] : %(message)s'
        },     
    },
    'handlers': {  
        'logit': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '/home/nextaps/logit.log',
#             'class': 'logging.handlers.TimedRotatingFileHandler', 
#             'filename': '/home/'+getpass.getuser()+'/logit.log',
            'when': 'midnight',
            'backupCount': 10, 
            'formatter': 'standard',  
        },   
    },  
    'loggers': {
        'logit': {      
            'handlers': ['logit'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
 
STATUS_KEY = "status"
SUCCESS_STATUS = "NTE_01"
FAILURE_STATUS = "NTE_02"
UPDATE_STATUS = "NTE_03"
REMOVE_STATUS = "NTE_04"
PASSWORD_UPDATE_STATUS = "NTE_05"
OTP_STATUS = "NTE_06"
PASSWORD_CHANGE = "NTE_24"
ERR0400 = "ERR0400"
ERR0401 = "ERR0401" 
ERR0403 = "ERR0403"
ERR0404 = "ERR0404"
ERR0405 = "ERR0405"
ERR0408 = "ERR0408"
ERR0500 = "ERR0500"
ERR0503 = "ERR0503"
ERR0600 = "ERR0600"
ERR0001 = "ERR0001"  
ERR0002 = "ERR0002"
ERR0003 = "ERR0003"
ERR0004 = "ERR0004"  
ERR0005 = "ERR0005"
ERR0006 = "ERR0006" 
ERR0007 = "ERR0007"
ERR0008 = "ERR0008"
ERR0009 = "ERR0009"
ERR0010 = "ERR0010" 
ERR0011 = "ERR0011"
ERR0012 = "ERR0012"
ERR0013 = "ERR0013"
ERR0014 = "ERR0014"
ERR0015 = "ERR0015"
ERR0016 = "ERR0016"
ERR0020 = "ERR0020"
ERR0021 = "ERR0021"
ERR0022 = "ERR0022"
ERR0023 = "ERR0023"
ERR0024 = "ERR0024"
ERR0025 = "ERR0025"
ERR0026 = "ERR0026"
ERR0027 = "ERR0027"
ERR0028 = "ERR0028"
ERR0029 = "ERR0029"
ERR0030 = "ERR0030"
ERR0031 = "ERR0031"
ERR0032 = "ERR0032"
ERR0043 = "ERR0043"

mobile_api_image_path = 'http://mynext.nexttechnosolutions.com/media/user_profile/'
image_path = 'http://mynext.nexttechnosolutions.com/media/user_profile/'
employee_offer_css = '/home/nextaps/NEXT_HCMS/static/ui/css/offer_document.css'
employee_payslip_css = '/home/nextaps/NEXT_HCMS/static/ui/css/payslip.css'


#Configuration for CS Module to project sync data from NPOWER
CS_NPOWER_DB_NAME = 'next_p5s_live'
CS_NPOWER_DB_HOST = '10.0.1.5'
CS_NPOWER_DB_USER = 'next'
CS_NPOWER_DB_PWD = 'next'
