balanced_scorecard_template='performance_management/balanced_scorecard.html'
exception='exception'
content_type_value='application/json'
performance_assessment_module='Performance_Management/performance_assessment'
fetch_organization_details_view='fetch_organization_details_view'
organization='organization'
fetch_org_unit_division_details='fetch_org_unit_division_details'
FINAN='FINAN_details'
CSTMR='CSTMR_details'
IPRCS='IPRCS_details'
LRNGR='LRNGR_details'
org_unit_FINAN='org_unit_FINAN_details'
org_unit_CSTMR='org_unit_CSTMR_details'
org_unit_IPRCS='org_unit_IPRCS_details'
org_unit_LRNGR='org_unit_LRNGR_details'

division_FINAN='division_FINAN_details'
division_CSTMR='org_unit_CSTMR_details'
division_IPRCS='division_IPRCS_details'
division_LRNGR='division_LRNGR_details'

prespective_FINAN='prespective_FINAN_details'
prespective_CSTMR='prespective_CSTMR_details'
prespective_IPRCS='prespective_IPRCS_details'
prespective_LRNGR='prespective_LRNGR_details'

fetch_ref_bsc='fetch_ref_bsc'
bsc_form_save='bsc_form_save'

objective_data_fetch='objective_data_fetch'

bsc_form_remove='bsc_form_remove'