data="data"
datas="datas"
country_key = "country"
status="status"
name='name'
telephone_number='telephone_number'
mobile_number='mobile_number'
email='email'
fax='fax'
address1='address1'
address2='address2'
country='country'
is_active='is_active'
created_by='created_by'
created_by_id='created_by_id'
modified_by='modified_by'
modified_by_id='modified_by_id'
status_key='status'
success_status="NTE_01"
failure_status="NTE_05"
updated_key="Updated Successfully"
delete_id='delete_id'
table_id='table_id'
status_already_exists='ERR0020'
create_org_unit_error='ERR0032'
update_status='NTE_03'
remove_status='NTE_04'
hrms_employee_list = "hrms_employee_list"
emp_name = "emp_name"
id = "id"
employee_management = "employee_management"
results = "results"
date_time_format = "%d-%m-%Y %H:%M"
update_flag="update_flag"
delete_list="delete_list"
employee_id="employee_id"
#attachment
format = "format"
img_name = "img_name"
img_str = "img_str"
hrms_attachment_max_id = "hrms_attachment_max_id"
hrms_attachment_insert = "hrms_attachment_insert"
attachment_id = "attachment_id"
hrms_attachment_update = "hrms_attachment_update"
status_id = 'status_id'
#Employee Query
organization_info="organization_info"
role_info="role_info"
related_user_info="related_user_info"
reporting_officer_info="reporting_officer_info"
gender_info="gender_info"
marital_status_info="marital_status_info"
emp_type_info="emp_type_info"
team_info="team_info"
hrms_fetch_related_user_info="hrms_fetch_related_user_info"
hrms_fetch_organization_info="hrms_fetch_organization_info"
hrms_fetch_role_info="hrms_fetch_role_info"
hrms_fetch_reporting_officer_info="hrms_fetch_reporting_officer_info"
hrms_fetch_employee_info="hrms_fetch_employee_info"
hrms_fetch_employee_id="hrms_fetch_employee_id"
hrms_employee_row_click="hrms_employee_row_click"
hrms_fetch_employee_skill_details="hrms_fetch_employee_skill_details"
hrms_fetch_employee_education_details="hrms_fetch_employee_education_details"
hrms_fetch_employee_experience_details="hrms_fetch_employee_experience_details"
hrms_fetch_employee_certification_details="hrms_fetch_employee_certification_details"
hrms_fetch_team_name_info = "hrms_fetch_team_name_info"
# Organization query
hrms_fetch_organization_details="hrms_fetch_organization_details"
hrms_organization_row_click="hrms_organization_row_click"
hrms_reporting_officer_search_list="hrms_reporting_officer_search_list"
# Employee reporting officer search
f_name = "f_name"
l_name = "l_name"
g_name = "g_name"
id_no = "id_no"
org_ids = "org_ids"
org_unit_id = "org_unit_id"
hrms_fetch_role_drop_down = "hrms_fetch_role_drop_down"
hrms_check_related_user_id_exists = "hrms_check_related_user_id_exists"
#employee list
unit_id = 'unit_id'
record_already_referred = 'ERR0028'
title_info = 'title_info'
grade_info = 'grade_info'
disability_category_info = 'disability_category_info'
blood_group_info = 'blood_group_info'
attendance_options_info = 'attendance_options_info'
hrms_employee_get_gen_type = 'hrms_employee_get_gen_type'
hrms_doc_employee_event_list = "hrms_doc_employee_event_list"
user = "user"
input_data = "input_data"
del_id = "del_id" 
results = 'results'
hrms_attachment_doc_insert = "hrms_attachment_doc_insert"
hrms_attachment_doc_details = "hrms_attachment_doc_details"
doc_type_id = "doc_type_id"
attendance_management = "attendance_management"
hrms_org_list = "hrms_org_list"
hrms_past_doc_details = "hrms_past_doc_details"
emp_list = "emp_list"
org_unit_id = "org_unit_id"
org_id = "org_id"
ref_id = "ref_id"
#Dashboard
powerbar1 = "powerbar1"
container2 = "container2"
hrms_employee_assets_list = 'hrms_employee_assets_list'
hrms_assets_check = 'hrms_assets_check'
hrms_assets_list_for_employee = 'hrms_assets_list_for_employee'
hrms_assets_list = 'hrms_assets_list'
hrms_insert_asset_details = 'hrms_insert_asset_details'
hrms_update_asset_details = 'hrms_update_asset_details'
folder_name = 'folder_name'
disability_percentage_info = 'disability_percentage_info'
skill_type_info = 'skill_type_info'
shift_type_info = 'shift_type_info'
org_name = 'org_name'
hrms_org_search_list = 'hrms_org_search_list'
org_unit_info = 'org_unit_info'
hrms_fetch_org_unit_info = 'hrms_fetch_org_unit_info'
province_info = 'province_info'
hrms_organization_list_province = 'hrms_organization_list_province'
hrms_employee_list_country_code = 'hrms_employee_list_country_code'
hrms_check_organization_name = 'hrms_check_organization_name'
hrms_country_drop_down = 'hrms_country_drop_down'
country_id = 'country_id'
asset_type_info = 'asset_type_info'
asset_id_info = 'asset_id_info'
hrms_asset_id_drop_down = 'hrms_asset_id_drop_down'
asset_type_id = 'asset_type_id'
hrms_fetch_employee_assets = 'hrms_fetch_employee_assets'
asset_id = 'asset_id'
hrms_check_asset_already_allocated = 'hrms_check_asset_already_allocated'
hrms_fetch_parent_org_unit_info = "hrms_fetch_parent_org_unit_info"
hrms_mobile_number_already = "hrms_mobile_number_already"
mobile_number = "mobile_numbers"
emp_id = "emp_id"
hrms_pf_number_already = "hrms_pf_number_already"
pf_numbers = "pf_numbers"
award_info = 'award_info'
hrms_select_employee_info = 'hrms_select_employee_info'
employee_info = 'employee_data'
