#-----------Department Config Start-----------------#
employee="EmployeeManaement"
department_table = 'department_table'#query for table
company_result = 'company_result'
department_result = 'department_result'
department_row_click = 'department_row_click'#query for row click
department_row_datas = ['id','description','company_id','parent_id']
department_url_name = "Employee/hr_department.html"
department_table_keys = ['id','row_number','description','company_id_id','code']
department_json_data_keys = 'datas'
keys_company = ['id','name']
company_list = 'comapny_datas'
department_keys = ['id','name']
departmentkeys = 'parent_datas'
department_delete = 'hr_department'
datas = "results"
department_id = 'id'
status='status'
company='company'
delete_id = "delete_id"
org_unit_id="org_unit_id"
add_success = "NTE_01"
update_success = "NTE_03"
delete_success = "NTE_04"
results = "results"
update_id = "update_id"
error = "NTE-02"
department_name='department_name'
department_name_check='department_name_check'
department_name_check_update='department_name_check_update'
id='id'
code='code'
name='name'
description='description'
country_name='country_name'
company_id_id='company_id_id'
row_number='row_number'
user_role_id = "user_role_id"
user_role_data_key = 'user_role_data_key'
role_data = 'data_result'
department_name_key = 'department_name_key'
company_name_key = 'company_name_key'
company_id_key = 'company_id_key'
#------------Department Config End-----------------#