data="data"
datas="datas"
country_key = "country"
value="value"
delete_id="delete_id"
table_id="table_id"
status_already_exists='ERR0020'
update_status='NTE_03'
remove_status='NTE_04'
is_active='is_active'
created_by='created_by'
created_by_id='created_by_id'
modified_by='modified_by'
modified_by_id='modified_by_id'
status_key='status'
success_status="NTE_01"
failure_status="NTE_05"
updated_key="Updated Successfully"
hrms_fetch_team_details="hrms_fetch_team_details"
status="status"
employee_management = "employee_management"
hrms_fetch_team_details_rowclick="hrms_fetch_team_details_rowclick"
hrms_fetch_team_details_max_id = 'hrms_fetch_team_details_max_id'