# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_management', '0001_initial'),
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Mgt_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_model_code', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_configuration', models.TextField(blank=True, null=True)),
                ('asset_serial', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('asset_warranty', models.IntegerField(blank=True, null=True)),
                ('asset_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('asset_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_address', models.TextField(blank=True, null=True)),
                ('asset_brown_goods', models.TextField(blank=True, null=True)),
                ('asset_white_goods', models.TextField(blank=True, null=True)),
                ('asset_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_division', to='organization_management.TeamDetails')),
                ('asset_make_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='make_reference_item', to='system_admin.Reference_Items')),
                ('asset_model_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_reference_item', to='system_admin.Reference_Items')),
                ('asset_model_type_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_type_reference_item', to='system_admin.Reference_Items')),
                ('asset_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_org', to='organization_management.OrganizationInfo')),
                ('asset_org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_org_unit', to='organization_management.OrganizationUnit')),
                ('asset_status_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_reference_item', to='system_admin.Reference_Items')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_asset_management_asset_mgt_list_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_asset_management_asset_mgt_list_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_am_asset_list',
            },
        ),
    ]
