# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-08-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_auto_20181114_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hrprofessionalexperiencesinfo',
            name='hr_contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
