# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_management', '0001_initial'),
        ('system_admin', '0001_initial'),
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttandanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('timesheet_id', models.IntegerField(blank=True, null=True)),
                ('entry_type', models.BooleanField(default=False)),
                ('in_hrs', models.CharField(blank=True, max_length=20, null=True)),
                ('work_time', models.IntegerField(blank=True, null=True)),
                ('punchin_1', models.DateTimeField(blank=True, null=True)),
                ('punchin_2', models.DateTimeField(blank=True, null=True)),
                ('punchin_3', models.DateTimeField(blank=True, null=True)),
                ('punchin_4', models.DateTimeField(blank=True, null=True)),
                ('punchin_5', models.DateTimeField(blank=True, null=True)),
                ('punchin_6', models.DateTimeField(blank=True, null=True)),
                ('punchin_7', models.DateTimeField(blank=True, null=True)),
                ('punchin_8', models.DateTimeField(blank=True, null=True)),
                ('punchin_9', models.DateTimeField(blank=True, null=True)),
                ('punchin_10', models.DateTimeField(blank=True, null=True)),
                ('punchin_11', models.DateTimeField(blank=True, null=True)),
                ('punchin_12', models.DateTimeField(blank=True, null=True)),
                ('punchin_13', models.DateTimeField(blank=True, null=True)),
                ('punchin_14', models.DateTimeField(blank=True, null=True)),
                ('punchin_15', models.DateTimeField(blank=True, null=True)),
                ('punchout_1', models.DateTimeField(blank=True, null=True)),
                ('punchout_2', models.DateTimeField(blank=True, null=True)),
                ('punchout_3', models.DateTimeField(blank=True, null=True)),
                ('punchout_4', models.DateTimeField(blank=True, null=True)),
                ('punchout_5', models.DateTimeField(blank=True, null=True)),
                ('punchout_6', models.DateTimeField(blank=True, null=True)),
                ('punchout_7', models.DateTimeField(blank=True, null=True)),
                ('punchout_8', models.DateTimeField(blank=True, null=True)),
                ('punchout_9', models.DateTimeField(blank=True, null=True)),
                ('punchout_10', models.DateTimeField(blank=True, null=True)),
                ('punchout_11', models.DateTimeField(blank=True, null=True)),
                ('punchout_12', models.DateTimeField(blank=True, null=True)),
                ('punchout_13', models.DateTimeField(blank=True, null=True)),
                ('punchout_14', models.DateTimeField(blank=True, null=True)),
                ('punchout_15', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_attendance_management_attandanceinfo_related', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.EmployeeInfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_attendance_management_attandanceinfo_related', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_management.OrganizationInfo')),
                ('org_team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_division_attendance_balance', to='organization_management.TeamDetails')),
                ('org_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_unit_attendance_balance', to='organization_management.OrganizationUnit')),
            ],
            options={
                'ordering': ['employee_id'],
                'db_table': 'attendance_info',
            },
        ),
        migrations.CreateModel(
            name='HolidayListInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('holiday_information', models.CharField(blank=True, max_length=100, null=True)),
                ('holiday_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_attendance_management_holidaylistinfo_related', to=settings.AUTH_USER_MODEL)),
                ('holiday_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.Reference_Items')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_attendance_management_holidaylistinfo_related', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_companyname', to='organization_management.OrganizationInfo')),
                ('org_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_unit_holiday', to='organization_management.OrganizationUnit')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_year_ref', to='system_admin.Reference_Items')),
            ],
            options={
                'ordering': ['holiday_information'],
                'db_table': 'holiday_list_info',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('leave_days', models.FloatField(blank=True, max_length=10, null=True)),
                ('allocated_leave_days', models.FloatField(blank=True, max_length=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_attendance_management_leavebalanceinfo_related', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.EmployeeInfo')),
                ('leave_company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leavebalance_companyname', to='organization_management.OrganizationInfo')),
                ('leave_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.Reference_Items')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_attendance_management_leavebalanceinfo_related', to=settings.AUTH_USER_MODEL)),
                ('org_unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_unit_leave_balance', to='organization_management.OrganizationUnit')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_of_leave_balance', to='system_admin.Reference_Items')),
            ],
            options={
                'ordering': ['employee_id'],
                'db_table': 'leave_balance_info',
            },
        ),
        migrations.CreateModel(
            name='LeaveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_days', models.FloatField(blank=True, max_length=10, null=True)),
                ('reason', models.CharField(blank=True, max_length=300, null=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_attendance_management_leaveinfo_related', to=settings.AUTH_USER_MODEL)),
                ('leave_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.EmployeeInfo')),
                ('leave_org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_companyname', to='organization_management.OrganizationInfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_attendance_management_leaveinfo_related', to=settings.AUTH_USER_MODEL)),
                ('reject_reason_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reject_id', to='system_admin.Reference_Items')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_id', to='system_admin.Reference_Items')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.Reference_Items')),
            ],
            options={
                'ordering': ['description'],
                'db_table': 'leave_info',
            },
        ),
        migrations.AddIndex(
            model_name='leaveinfo',
            index=models.Index(fields=['description'], name='leave_info_descrip_0f9d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalanceinfo',
            index=models.Index(fields=['employee_id'], name='leave_balan_employe_79971d_idx'),
        ),
        migrations.AddIndex(
            model_name='holidaylistinfo',
            index=models.Index(fields=['holiday_information'], name='holiday_lis_holiday_02d4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='attandanceinfo',
            index=models.Index(fields=['employee_id'], name='attendance__employe_d259d0_idx'),
        ),
    ]
