# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_management', '0001_initial'),
        ('talent_inventory', '0001_initial'),
        ('system_admin', '0001_initial'),
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCMS_TA_Assessment_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_form_assessment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('assessment_form_finalised_status', models.BooleanField(default=False)),
                ('assessment_category_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_form_assessment_category_refitem', to='system_admin.Reference_Items')),
                ('assessment_form_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_form_employee_id', to='employee_management.EmployeeInfo')),
                ('assessment_form_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Role_Details')),
            ],
            options={
                'db_table': 'hcms_ta_assessment_form',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Assessment_Form_KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_form_kpi_type', models.CharField(blank=True, max_length=20, null=True)),
                ('assessment_form_kpi_expected', models.IntegerField(blank=True, null=True)),
                ('assessment_form_kpi_measurement_criteria', models.TextField(blank=True, null=True)),
                ('assessment_form_kpi_weightage', models.IntegerField(blank=True, null=True)),
                ('assessment_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_Assessment_Form')),
            ],
            options={
                'db_table': 'hcms_ta_assessment_form_kpi',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Assessment_Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_process_kpi_type', models.CharField(blank=True, max_length=30, null=True)),
                ('assessment_process_remark', models.TextField(blank=True, null=True)),
                ('assessment_process_assessment_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_Assessment_Form')),
                ('assessment_process_assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_process_assessor_id', to='employee_management.EmployeeInfo')),
                ('assessment_process_assessor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessor_type_assessment_category_refitem', to='system_admin.Reference_Items')),
                ('assessment_process_custom_rating_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Custom_Rating_Scheme')),
                ('assessment_process_custom_rating_scheme_rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Custom_Rating_Scheme_Relation')),
                ('assessment_process_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_process_employee_id', to='employee_management.EmployeeInfo')),
                ('assessment_process_form_kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_form_kpi', to='talent_assessment.HCMS_TA_Assessment_Form_KPI')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_assessment_process_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_assessment_process_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ta_assessment_process',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Assessment_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_schedule_name', models.TextField(blank=True, null=True)),
                ('assessment_schedule_cycle_starts', models.DateField(blank=True, null=True)),
                ('assessment_schedule_cycle_ends', models.DateField(blank=True, null=True)),
                ('assessment_schedule_objective_setting_day_count', models.IntegerField(blank=True, null=True)),
                ('assessment_objective_setting_date', models.DateField(blank=True, null=True)),
                ('assessment_schedule_assessment_category_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedule_category_refitem_id', to='system_admin.Reference_Items')),
                ('assessment_schedule_employee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_type_refitem_id', to='system_admin.Reference_Items')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_assessment_schedule_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_assessment_schedule_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ta_assessment_schedule',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Assessment_Schedule_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_schedule_assess_type_day_count', models.IntegerField(blank=True, null=True)),
                ('assessment_schedule_start_date', models.DateField(blank=True, null=True)),
                ('assessment_schedule_sequence', models.IntegerField(blank=True, null=True)),
                ('assessment_assessor_type_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedule_details_assessor_type_refitem_id', to='system_admin.Reference_Items')),
                ('assessment_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_Assessment_Schedule')),
                ('assessment_schedule_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedule_employee_id', to='employee_management.EmployeeInfo')),
                ('assessment_schedule_status_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedule_status_refitem_id', to='system_admin.Reference_Items')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_assessment_schedule_details_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_assessment_schedule_details_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ta_assessment_schedule_details',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Assessment_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_template_name', models.TextField(blank=True, null=True)),
                ('assessment_template_code', models.CharField(blank=True, max_length=20, null=True)),
                ('assessment_template_active_status', models.BooleanField(default=False)),
                ('assessment_template_publish_status', models.BooleanField(default=False)),
                ('assessment_category_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_template_assessment_category_refitem', to='system_admin.Reference_Items')),
                ('assessment_template_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessor_template_role_id', to='talent_inventory.HCMS_TI_Role_Details')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_assessment_template_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_assessment_template_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ta_assessment_template',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Assessment_Template_KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessment_template_kpi_type', models.CharField(blank=True, max_length=20, null=True)),
                ('assessment_template_kpi_expected', models.IntegerField(blank=True, null=True)),
                ('assessment_template_kpi_weightage', models.IntegerField(blank=True, null=True)),
                ('assessment_template_kpi_measurement_criteria', models.TextField(blank=True, null=True)),
                ('assessment_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_Assessment_Template')),
            ],
            options={
                'db_table': 'hcms_ta_assessment_template_kpi',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Assessor_Access_Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessor_access', models.BooleanField()),
                ('assessor_view_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessor_view_role_id', to='system_admin.Reference_Items')),
                ('assessor_viewer_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessor_viewer_role_id', to='system_admin.Reference_Items')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_assessor_access_matrix_related', to=settings.AUTH_USER_MODEL)),
                ('hcms_tm_assessment_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_Assessment_Form')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_assessor_access_matrix_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ta_assessor_access_matrix',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Assessor_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assessor_assessment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.EmployeeInfo')),
                ('assessor_assessment_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_Assessment_Form')),
                ('assessor_type_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_info_assessor_type_refitem', to='system_admin.Reference_Items')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_assessor_info_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_assessor_info_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ta_assessor_info',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kpi_description', models.TextField(blank=True, null=True)),
                ('kpi_target_type', models.CharField(blank=True, max_length=100, null=True)),
                ('kpi_target_value', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_kpi_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ta_kpi',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Linked_Objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_linked_objectives_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_linked_objectives_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ta_linked_objectives',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Objective_OrgUnit_Rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_objective_orgunit_rel_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_objective_orgunit_rel_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ta_objective_orgunit_rel',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Performance_Potential_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('performance_score', models.IntegerField(blank=True, null=True)),
                ('potential_score', models.IntegerField(blank=True, null=True)),
                ('assessment_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_category_ref_id', to='system_admin.Reference_Items')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_performance_potential_info_related', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_potential_employee_id', to='employee_management.EmployeeInfo')),
                ('employee_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_form_id', to='talent_assessment.HCMS_TA_Assessment_Form')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_performance_potential_info_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ta_performance_potential_info',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Report_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_config_filter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('report_config_filter_data', models.TextField(blank=True, null=True)),
                ('report_config_ref_sequence', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_report_config_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_report_config_related', to=settings.AUTH_USER_MODEL)),
                ('report_config_filter_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.Reference_Items')),
            ],
            options={
                'db_table': 'hcms_ta_report_config',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Report_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_master_entity', models.CharField(blank=True, max_length=100, null=True)),
                ('report_master_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_report_master_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_report_master_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hcms_ta_report_master',
            },
        ),
        migrations.CreateModel(
            name='HCMS_TA_Strategic_Objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('strategic_objective_driver', models.TextField(blank=True, null=True)),
                ('strategic_objective_description', models.TextField(blank=True, null=True)),
                ('strategic_objective_action_to_achieve', models.TextField(blank=True, null=True)),
                ('strategic_objective_start_date', models.DateField(blank=True, null=True)),
                ('strategic_objective_end_date', models.DateField(blank=True, null=True)),
                ('strategic_objective_expected_outcome', models.TextField(blank=True, null=True)),
                ('strategic_objective_budget', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_strategic_objectives_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_strategic_objectives_related', to=settings.AUTH_USER_MODEL)),
                ('strategic_bsc_perspective_type_refitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balancescore_card_perspective_refitem', to='system_admin.Reference_Items')),
                ('strategic_objective_budget_currency_type_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_type_refitem', to='system_admin.Reference_Items')),
                ('strategic_objective_driver_exist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_Strategic_Objectives')),
            ],
            options={
                'db_table': 'hcms_ta_strategic_objectives',
            },
        ),
        migrations.AddField(
            model_name='hcms_ta_report_config',
            name='report_config_master_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_config_master_id', to='talent_assessment.HCMS_TA_Report_Master'),
        ),
        migrations.AddField(
            model_name='hcms_ta_objective_orgunit_rel',
            name='strategic_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_Strategic_Objectives'),
        ),
        migrations.AddField(
            model_name='hcms_ta_objective_orgunit_rel',
            name='strategic_objective_orgunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_management.OrganizationUnit'),
        ),
        migrations.AddField(
            model_name='hcms_ta_objective_orgunit_rel',
            name='strategic_objective_role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Role_Details'),
        ),
        migrations.AddField(
            model_name='hcms_ta_linked_objectives',
            name='strategic_objective_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_strategic_objective', to='talent_assessment.HCMS_TA_Strategic_Objectives'),
        ),
        migrations.AddField(
            model_name='hcms_ta_linked_objectives',
            name='strategic_objective_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_strategic_objective', to='talent_assessment.HCMS_TA_Strategic_Objectives'),
        ),
        migrations.AddField(
            model_name='hcms_ta_kpi',
            name='hcms_tm_strategic_objectives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_Strategic_Objectives'),
        ),
        migrations.AddField(
            model_name='hcms_ta_kpi',
            name='kpi_custom_rating_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Custom_Rating_Scheme'),
        ),
        migrations.AddField(
            model_name='hcms_ta_kpi',
            name='kpi_tracking_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_tracking_type_refitem', to='system_admin.Reference_Items'),
        ),
        migrations.AddField(
            model_name='hcms_ta_kpi',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_kpi_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_ta_assessment_template_kpi',
            name='assessment_template_cascaded_kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_KPI'),
        ),
        migrations.AddField(
            model_name='hcms_ta_assessment_template_kpi',
            name='assessment_template_role_kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Role_KPI'),
        ),
        migrations.AddField(
            model_name='hcms_ta_assessment_template_kpi',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_assessment_template_kpi_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_ta_assessment_template_kpi',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_assessment_template_kpi_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_ta_assessment_form_kpi',
            name='assessment_form_cascaded_kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_KPI'),
        ),
        migrations.AddField(
            model_name='hcms_ta_assessment_form_kpi',
            name='assessment_form_role_kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_inventory.HCMS_TI_Role_KPI'),
        ),
        migrations.AddField(
            model_name='hcms_ta_assessment_form_kpi',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_assessment_form_kpi_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_ta_assessment_form_kpi',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_assessment_form_kpi_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_ta_assessment_form',
            name='assessment_form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent_assessment.HCMS_TA_Assessment_Template'),
        ),
        migrations.AddField(
            model_name='hcms_ta_assessment_form',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_talent_assessment_hcms_ta_assessment_form_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hcms_ta_assessment_form',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_talent_assessment_hcms_ta_assessment_form_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
