# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EM_ExitDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('emp_resignation_date', models.DateField(blank=True, null=True)),
                ('emp_leaving_reason_refitem', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('emp_leaving_reason_others', models.TextField(blank=True, null=True)),
                ('emp_remarks', models.TextField(blank=True, null=True)),
                ('emp_exp_relieving_date', models.DateField(blank=True, null=True)),
                ('department_approve_status', models.BooleanField(default=False)),
                ('department_remarks', models.TextField(blank=True, null=True)),
                ('emp_status', models.BooleanField(default=False)),
                ('hr_approve_status', models.BooleanField(default=False)),
                ('hr_remarks', models.TextField(blank=True, null=True)),
                ('hr_relieving_date', models.DateField(blank=True, null=True)),
                ('hr_emp_status', models.BooleanField(default=False)),
                ('emp_asset_clearance', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), null=True, size=None)),
                ('department_clearance', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), null=True, size=None)),
                ('adimn_clearance', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), null=True, size=None)),
                ('account_clearance', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), null=True, size=None)),
                ('network_clearance', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), null=True, size=None)),
                ('hr_clearance', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), null=True, size=None)),
                ('relieving_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_exit_management_em_exitdetails_related', to=settings.AUTH_USER_MODEL)),
                ('department_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrms_department_employee_id', to='employee_management.EmployeeInfo')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrms_employee_id', to='employee_management.EmployeeInfo')),
                ('hr_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hrms_hr_employee_id', to='employee_management.EmployeeInfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_exit_management_em_exitdetails_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['emp'],
                'db_table': 'em_exit_details',
            },
        ),
        migrations.CreateModel(
            name='EM_ExitDetailsCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exit_file_name', models.TextField(blank=True, null=True)),
                ('exit_file_path', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_exit_management_em_exitdetailscertification_related', to=settings.AUTH_USER_MODEL)),
                ('exit_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_employee_id', to='exit_management.EM_ExitDetails')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_exit_management_em_exitdetailscertification_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exit_file_name'],
                'db_table': 'em_exit_certificate_details',
            },
        ),
        migrations.AddIndex(
            model_name='em_exitdetailscertification',
            index=models.Index(fields=['exit_emp'], name='em_exit_cer_exit_em_20190a_idx'),
        ),
        migrations.AddIndex(
            model_name='em_exitdetails',
            index=models.Index(fields=['emp'], name='em_exit_det_emp_id_7c4e57_idx'),
        ),
    ]
