# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-14 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipReturnValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lvr_name', models.CharField(max_length=100, null=True)),
                ('value_return', models.FloatField(null=True)),
                ('leadership_date_from', models.DateTimeField(null=True)),
                ('leadership_date_to', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_payroll_management_leadershipreturnvalue_related', to=settings.AUTH_USER_MODEL)),
                ('leadership_slab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_slab', to='payroll_management.RatingPoint')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_payroll_management_leadershipreturnvalue_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lvr_name'],
                'db_table': 'leadership_value_return',
            },
        ),
        migrations.CreateModel(
            name='PayrollActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_name', models.TextField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('field_name', models.TextField(null=True)),
                ('new_value', models.TextField(null=True)),
                ('old_value', models.TextField(null=True)),
                ('form_name', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_payroll_management_payrollactivitylog_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_payroll_management_payrollactivitylog_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
                'db_table': 'payroll_activity_log',
            },
        ),
        migrations.AlterField(
            model_name='payrollmonthlyreport',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollmonthlyreport',
            name='finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollmonthlyreport',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollmonthlyreport',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollmonthlyreportemailcount',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
