# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HCMSOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_value', models.CharField(blank=True, max_length=100, null=True)),
                ('is_otp_expired', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'hcms_otp',
            },
        ),
        migrations.CreateModel(
            name='jenkins_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_build_number', models.IntegerField(blank=True, null=True)),
                ('last_build_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jenkins_api',
            },
        ),
        migrations.CreateModel(
            name='Newsapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('newsapi_source', models.CharField(blank=True, max_length=100, null=True)),
                ('newsapi_articles', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('newsapi_title', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'news_api',
            },
        ),
        migrations.AddIndex(
            model_name='jenkins_api',
            index=models.Index(fields=['last_build_number'], name='jenkins_api_index'),
        ),
        migrations.AddField(
            model_name='hcmsotp',
            name='otp_mail_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
