content_type_value='application/json'
shift_module='Workforce_Administration/shift_management'
shift_master_save="shift_master_save"
shift_master_details='shift_master_details'
fetch_shift_details='fetch_shift_details'
shift_master_update='shift_master_update'
shift_master_remove='shift_master_remove'
org_unit_details='org_unit_details'
exsist_shift_details='exsist_shift_details'

shift_roster_insert="shift_roster_insert"
shift_roster_detail_fetch="shift_roster_detail_fetch"
shift_roster_detail_fetch_by_id="shift_roster_detail_fetch_by_id"
shift_roster_update="shift_roster_update"
shift_roster_detail_remove="shift_roster_detail_remove"
update_exsist_shift_details='update_exsist_shift_details'

role_based_employee_details = 'role_based_employee_details'
delete_shift_based_employee = "delete_shift_based_employee"
delete_shift_based_employees = "delete_shift_based_employees"
insert_shift_employee_rel = "insert_shift_employee_rel"
delete_shift_rel_based_shift = "delete_shift_rel_based_shift"
shift_employee_based_employee_details = "shift_employee_based_employee_details"
shift_employees_based_employee_details = "shift_employees_based_employee_details"
employee_based_employee_details = "employee_based_employee_details"
employees_based_employee_details = "employees_based_employee_details"
shift_details_view_based_shift = "shift_details_view_based_shift"
shift_details_table_view_based_shift = "shift_details_table_view_based_shift"
fetch_shift_details_id = "fetch_shift_details_id"
fetch_shift_details_based_orgunit = "fetch_shift_details_based_orgunit"
fetch_role_details_based_orgunit = "fetch_role_details_based_orgunit"
fetch_employee_details_based_division = "fetch_employee_details_based_division"
fetch_employee_details_view = "fetch_employee_details_view"
fetch_shift_details_view = 'fetch_shift_details_view'
fetch_organization_details_view = 'fetch_organization_details_view'
fetch_role_details_view = 'fetch_role_details_view'
divison_fetch_based_org_unit = "divison_fetch_based_org_unit"
shift_division_based_shift_details = "shift_division_based_shift_details"
role_id = "role_id"
null = "null"
status = "status"
role_data = "role_data"
NTE_08 = "NTE_08"
application_json ="application/json"
shift_name = "shift_name"
employee_name = "employee_name"
employee_name_common = "employee_name_common"
shift_details_id = "shift_details_id"
shift_id = "shift_id"
shift_name_id = "shift_name_id"
shift_detail = "shift_detail"
shift_employee_id = "shift_employee_id"
shift_data = 'shift_data'
fetch_data = 'fetch_data'
remove_id = 'remove_id'
org_unit = 'org_unit'
str_org_id = 'str_org_id'
org_unit_id = 'org_unit_id'
shift_details = 'shift_details'
role_details = 'role_details'
employee_details = 'employee_details'
organization_unit = 'organization_unit'
shift_description = 'shift_description'
shift_start = 'shift_start'
shift_end = 'shift_end'
work_half_day = 'work_half_day'
work_full_day = 'work_full_day'
clicked_row_id = 'clicked_row_id'
schedule_details = 'schedule_details'
shift_active = 'shift_active'
Exception = 'Exception'
organization = 'organization'
employee_info = 'employee_info'
shift_info = 'shift_info'
division_id = 'division_id'
role = 'role'
Shift_and_Scheduling = 'Shift and Scheduling'
tags_access_denied_html = "tags/access_denied.html"
shift_template_name = "workforce_administration/shift_schedule_management/shift_detail.html"
division_details='division_details'
shift_master_division_save='shift_master_division_save'
fetch_shift_division_details='fetch_shift_division_details'
shift_master_division_remove='shift_master_division_remove'
shift_master_division_delete='shift_master_division_delete'
check_exsist_shift_details_save='check_exsist_shift_details_save'
shift_master_division_rel_delete='shift_master_division_rel_delete'
check_update_exsist_shift_details='check_update_exsist_shift_details'