# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-26 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCMS_Shift_Employee_Rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_shift_management_hcms_shift_employee_rel_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_shift_management_hcms_shift_employee_rel_related', to=settings.AUTH_USER_MODEL)),
                ('shift_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.EmployeeInfo')),
                ('shift_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_management.HCMS_Shift_Master')),
            ],
            options={
                'db_table': 'hcms_shift_employee_rel',
            },
        ),
        migrations.CreateModel(
            name='HCMS_Shift_Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('roster_name', models.CharField(blank=True, max_length=50, null=True)),
                ('roster_description', models.TextField(blank=True, null=True)),
                ('roster_repeat_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('roster_weekly_pattern', models.TextField(blank=True, null=True)),
                ('roster_monthly_pattern', models.TextField(blank=True, null=True)),
                ('roster_end_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('roster_end_shift_occurence', models.IntegerField(blank=True, null=True)),
                ('roster_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_shift_management_hcms_shift_roster_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by_shift_management_hcms_shift_roster_related', to=settings.AUTH_USER_MODEL)),
                ('roster_rotation_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_rotation_from', to='employee_management.HCMS_Shift_Master')),
                ('roster_rotation_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roster_rotation_to', to='employee_management.HCMS_Shift_Master')),
            ],
            options={
                'db_table': 'hcms_shift_roster',
            },
        ),
    ]
