talent_inventory = "Talent_Inventory/talent_inventory"
refitems_data_fetch = "refitems_data_fetch"
ti_role_details_fetch = 'ti_role_details_fetch'
ti_role_details_view = 'ti_role_details_view'
ti_skill_set_view = 'ti_skill_set_view'
ti_critical_suc_fac_view = 'ti_critical_suc_fac_view'
ti_kpo_view = 'ti_kpo_view'
ti_kpi_view = 'ti_kpi_view'
ti_kpi_headers = 'ti_kpi_headers'
kpi_measure_freq_id = 'kpi_measure_freq_id'
custom_rate_id = 'custom_rate_id'
ti_role_details_id = 'ti_role_details_id'
KPI_update_delete = 'KPI_update_delete'
ti_reports_to_data='ti_reports_to_data'
ti_reports_struct_data='ti_reports_struct_data'
id='id'
role_title='role_title'
role_type='role_type'
role_reports_to_id='role_reports_to_id'
ti_compt_type='ti_compt_type'
role_exist_check = 'role_exist_check'
ti_role_type_fetch='ti_role_type_fetch'
ti_fetch_org_list='ti_fetch_org_list'
ti_fetch_org_unit_list='ti_fetch_org_unit_list'
ti_fetch_dept_list='ti_fetch_dept_list'
# 05-Mar-2018 || SMI || Dashboard Constants
ti_org_unit_types_count = 'ti_org_unit_types_count'
ti_uniq_emp_roles_count = 'ti_uniq_emp_roles_count'
ti_tech_comp_count = 'ti_tech_comp_count'
ti_func_comp_count = 'ti_func_comp_count'
ti_behv_comp_count = 'ti_behv_comp_count'
# 07-Mar-2018 || SMI || Dashboard Constants updated for charts
dash_chart1_all = 'dash_chart1_all'
dash_chart1 = 'dash_chart1'
tcc_dash_chart2 = 'tcc_dash_chart2'
fcc_dash_chart2 = 'fcc_dash_chart2'
bcc_dash_chart2 = 'bcc_dash_chart2'
#13-Mar-2018 || MST || For Role Title check
ti_role_title_check='ti_role_title_check'
#28-Mar-2018 || MST || For GIS Reports
ti_gis_reports='ti_gis_reports'
ti_gis_reports_role_title='ti_gis_reports_role_title'
