content_type_value='application/json'
attendance="Workforce_Administration/time_attendance_management"
shift_details='shift_details'
late_policy_save='late_policy_save'
late_policy_details="late_policy_details"
policy_details_show="policy_details_show"
late_policy_details="late_policy_details"
policy_period='policy_period'
lfa_add='lfa_add'
lfa_update='lfa_update'
lfa_leave_deduct_add='lfa_leave_deduct_add'
lfa_leave_deduct_remove='lfa_leave_deduct_remove'
leave_for_absent_detail_fetch='leave_for_absent_detail_fetch'
leave_for_absent_detail_fetch_by_id='leave_for_absent_detail_fetch_by_id'
leave_for_absent_detail_fetch_by_shift='leave_for_absent_detail_fetch_by_shift'
lfa_detail_remove='lfa_detail_remove'
late_policy_update='late_policy_update'
late_policy_remove='late_policy_remove'
shift_name_list = 'shift_name_list'
permission_apply = 'permission_apply'
permission_period = 'permission_period'
request_allowed = 'request_allowed'
permission_per_day = 'permission_per_day'
max_hours_allowed = 'max_hours_allowed'
permission_id = 'permission_id'
permission_details_id = 'permission_details_id'
shift_name_id = 'shift_name_id'
null = 'null'
return_id = 'return_id'
status = 'status'
NTE_08 = 'NTE_08'
application_json = 'application/json'
shift_details = 'shift_details'
permission_details = 'permission_details'
space = ''
permission_request_save = 'permission_request_save'
permission_details_view = 'permission_details_view'
permission_details_table_view = 'permission_details_table_view'
shift_change_details = 'shift_change_details'
permission_request_delete = 'permission_request_delete'
permission_request_update = 'permission_request_update'
return_data = 'return_data'
policy_shift_details_show='policy_shift_details_show'
policy_details_show_shift_change = "policy_details_show_shift_change"
attendance_detail_fetch='attendance_detail_fetch'
shift_detail_fetch='shift_detail_fetch'
fetch_data = "fetch_data"
division_details_shift_change = "division_details_shift_change"
shift_change = "shift_change"
attendance_date_series='attendance_date_series'
attendance_status_fetch="attendance_status_fetch"
permission_request_division_rel_delete = "permission_request_division_rel_delete"
permission_request_division_rel_save = "permission_request_division_rel_save"
permission_request_data_check = "permission_request_data_check"
late_policy_division_rel_delete = "late_policy_division_rel_delete"
late_policy_division_rel_save = "late_policy_division_rel_save"
division_id_list = "division_id_list"
shift_details_based_org_unit = "shift_details_based_org_unit"
division_details_based_org_unit = "division_details_based_org_unit"
division_id_list = "division_id_list"
late_policy_data_check = "late_policy_data_check"
