content_type_value='application/json'
learning_form_template='learning_management/cost_request_view.html'
learning_development_module='Learning_Management/learning_management'
organization = 'organization'

                                         # Cost and budget 
fetch_organization_details_view = 'fetch_organization_details_view'

cost_evaluation_template = 'learning_management/cost_evaluate.html'
fetch_organization_unit_details_view = 'fetch_organization_unit_details_view'
fetch_division_details_view = 'fetch_division_details_view'
ld_training_details = 'ld_training_details'
training_data = 'training_data'
cost_request_insert = 'cost_request_insert'
status = 'status'
ld_request = 'ld_request'
ld_approved ='ld_approved'
ld_rejected = 'ld_rejected'
datas = 'datas'
cost_request_table_view = 'cost_request_table_view'
role_details = 'role_details'
fetch_role_details ='fetch_role_details'
training_details='training_details'
ld_manager = 'ld_manager'
employee_user_details = 'employee_user_details'
budget_request_table_click ='budget_request_table_click'
cost_request_update ='cost_request_update'
budget_request_details = 'budget_request_details'
budget_status_update = 'budget_status_update'
budget_status_approval = 'budget_status_approval'
budget_status_approved = 'budget_status_approved'
budget_status_rejected ='budget_status_rejected'
budget_manager_details = 'budget_manager_details'
employee_user = 'employee_user'
cost_request_by_name = 'cost_request_by_name'
cost_request_insert_check = 'cost_request_insert_check'
budget_remove = 'budget_remove'
training_drop = 'training_drop'
data_load_organization = 'data_load_organization'
  
#                    Training creation
training_creation_template='learning_management/training_creation.html'
employee_org_id='employee_org_id'
exception='exception'
fetch_training_type='fetch_training_type'
fetch_training_method='fetch_training_method'
training_type_data='training_type_data'
training_method_data='training_method_data'
training_creation_save='training_creation_save'
training_division_save='training_division_save'
fetch_training_details='fetch_training_details'
training_detail_usage_check='training_detail_usage_check'
training_category_data='training_category_data'
fetch_training_category='fetch_training_category'

#                 """ Employee Self Request Config Start"""
employee_data = 'employee_data'
training_detail = 'training_detail'
training_id = 'training_id'
request_type = 'request_type'
training_id = 'training_id'
training_name = 'training_name'
manager_name = 'manager_name'
reason_for_training = 'reason_for_training'
remarks = 'remarks'
approval_status = 'approval_status'
E = "E"
N = "N"
A = "A"
R = "R"
id = "id"
manager_id = 'manager_id'
rejection_reason = 'rejection_reason'
organization_detail = 'organization_detail'
organization_unit_detail = 'organization_unit_detail'
division_detail = 'division_detail'
org_id = 'org_id'
orgunit_id = 'orgunit_id'
division_id = 'division_id'
training_search_detail = 'training_search_detail'
#                        <--Query String Start-->
ld_fetch_employee_data_division = 'ld_fetch_employee_data_division'
ld_fetch_training_detail_based_id = 'ld_fetch_training_detail_based_id'
ld_employee_request_training_save = 'ld_employee_request_training_save'
ld_employee_request_training_update = 'ld_employee_request_training_update'
ld_fetch_self_training_details = 'ld_fetch_self_training_details'
ld_fetch_request_training_detail_based_id = 'ld_fetch_request_training_detail_based_id'
ld_delete_request_training_detail_based_id = 'ld_delete_request_training_detail_based_id'
ld_fetch_request_training_count = 'ld_fetch_request_training_count'
training_count_detail = 'training_count_detail'
ld_fetch_organization_detail = 'ld_fetch_organization_detail'
ld_fetch_organization_unit_detail_org = 'ld_fetch_organization_unit_detail_org'
ld_fetch_division_detail_orgunit = 'ld_fetch_division_detail_orgunit'
ld_fetch_training_detail_division = 'ld_fetch_training_detail_division'
ld_fetch_request_training_detail_search = 'ld_fetch_request_training_detail_search'
tl_training_recommendation_detail_fetch_by_id='tl_training_recommendation_detail_fetch_by_id'
#                        <--Query String End-->

#                 """ Employee Self Request Config End"""

training_fetch_training_details='training_fetch_training_details'
training_form_remove='training_form_remove'
training_division_remove='training_division_remove'
selected_training_details='selected_training_details'
division_org_fetch='division_org_fetch'
training_division_delete='training_division_delete'
selected_training_attachment_details='selected_training_attachment_details'
training_attachment_remove='training_attachment_remove'

#                       Internship 
interrnship_template='learning_management/Internship.html'
fetch_country_details_view='fetch_country_details_view'
fetch_org_unit_division_details='fetch_org_unit_division_details'
fetch_org_unit_employee_details='fetch_org_unit_employee_details'
fetch_division_training_details='fetch_division_training_details'
internship_training_details='internship_training_details'
internship_state_details='internship_state_details'
internship_form_save='internship_form_save'
internship_details='internship_details'
selected_internship_details='selected_internship_details'
internship_form_remove='internship_form_remove'
convert_to_employee='convert_to_employee'

learning_developemnt='Learning And Development'
tags_access_denied_html = "tags/access_denied.html"

#                   dashboard
training_dashboard_template='learning_management/dashboard.html'
calander_training_details='calander_training_details'
calander_training_details_count='calander_training_details_count'
cost_details='cost_details'
rec_emp_details='rec_emp_details'
top_rec_person='top_rec_person'
self_request='self_request'
current_user_detaills='current_user_detaills'
gant_chart='gant_chart'
                                         # Training Recommendation
general_training_recommendation_template = 'learning_management/general_training_recommendation.html'
management_training_recommendation_template = 'learning_management/management_training_recommendation.html'
tl_training_recommendation_template = 'learning_management/tl_training_recommendation.html'
fetch_organization_details_view = 'fetch_organization_details_view'
ld_division_load='ld_division_load'
ld_employee_fetch='ld_employee_fetch'
ld_training_fetch='ld_training_fetch'
ld_training_detail_fetch='ld_training_detail_fetch'
ld_training_recommendation_insert='ld_training_recommendation_insert'
ld_training_recommendation_rel_insert='ld_training_recommendation_rel_insert'
ld_training_recommendation_detail_fetch='ld_training_recommendation_detail_fetch'
status='status'
ld_training_recommendation_rel_delete='ld_training_recommendation_rel_delete'
ld_training_recommendation_update='ld_training_recommendation_update'
ld_training_recommendation_detail_fetch_by_id='ld_training_recommendation_detail_fetch_by_id'
ld_training_recommendation_detail_remove='ld_training_recommendation_detail_remove'
ld_training_recommendation_rel_detail_remove='ld_training_recommendation_rel_detail_remove'
ld_training_recommendation_search_detail_fetch='ld_training_recommendation_search_detail_fetch'
ld_tl_assessment_training_list='ld_tl_assessment_training_list'
ld_tl_assessment_training_employee_details='ld_tl_assessment_training_employee_details'
tl_training_recommendation_insert='tl_training_recommendation_insert'
tl_training_recommendation_detail_fetch='tl_training_recommendation_detail_fetch'
tl_training_recommendation_search_detail_fetch='tl_training_recommendation_search_detail_fetch'
ld_tl_assessment_training_exist_check='ld_tl_assessment_training_exist_check'
tl_training_recommendation_update='tl_training_recommendation_update'
ld_tl_recommendation_training_creation='ld_tl_recommendation_training_creation'
ld_tl_recommendation_training_division_update='ld_tl_recommendation_training_division_update'
ld_tl_assessor_detail_update='ld_tl_assessor_detail_update'
                                         # Training Results
training_results_template = 'learning_management/training_results.html'
